#!/usr/bin/fish

if test "$argv[1],$argv[3],$argv[4]" = "keyboard,connected,Keychron K2 Keyboard"
    setxkbmap -layout us -variant altgr-intl -option altwin:swap_lalt_lwin -option caps:backspace
end
